name: ci

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.regex-match.outputs.match }}
    steps:
    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref_name }}
        regex: '^v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?$'
    - name: Print setup
      run: |
        echo github.ref=${{ github.ref }}
        echo github.ref_name=${{ github.ref_name }}
        echo github.ref_type=${{ github.ref_type }}
        echo release-ref=${{ steps.regex-match.outputs.match }}

  test270:
    runs-on: ubuntu-latest
    container:
      image: cimg/go:1.22
      env:
        GO111MODULE: "on"
        KAFKA_TOPICS_TEST_ZK_ADDR: zookeeper:2181
        KAFKA_TOPICS_TEST_KAFKA_ADDR: kafka1:9092
    steps:
    - name: Check out repository code 
      uses: actions/checkout@v3
    - name: Go setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Display Go version
      run: go version
    - name: Run tests
      run: make test-v2
      env:
        KAFKA_TOPICS_TEST_ZK_ADDR: zookeeper:2181
        KAFKA_TOPICS_TEST_KAFKA_ADDR: kafka1:9092
        KAFKA_TOPICS_TEST_BROKER_ADMIN_SECURITY: 1

    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - "2181:2181"
        env:
          ALLOW_ANONYMOUS_LOGIN: yes

      kafka1:
        image: bitnami/kafka:2.7.0
        ports:
          - "9092:9092"
        env:
          KAFKA_CFG_BROKER_ID: 1
          KAFKA_CFG_BROKER_RACK: zone1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka1
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka2:
        image: bitnami/kafka:2.7.0
        ports:
          - "9093:9092"
        env:
          KAFKA_CFG_BROKER_ID: 2
          KAFKA_CFG_BROKER_RACK: zone1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka2
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka3:
        image: bitnami/kafka:2.7.0
        ports:
          - "9094:9092"
        env:
          KAFKA_CFG_BROKER_ID: 3
          KAFKA_CFG_BROKER_RACK: zone2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka3
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka4:
        image: bitnami/kafka:2.7.0
        ports:
          - "9095:9092"
        env:
          KAFKA_CFG_BROKER_ID: 4
          KAFKA_CFG_BROKER_RACK: zone2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka4
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka5:
        image: bitnami/kafka:2.7.0
        ports:
          - "9096:9092"
        env:
          KAFKA_CFG_BROKER_ID: 5
          KAFKA_CFG_BROKER_RACK: zone3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka5
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka6:
        image: bitnami/kafka:2.7.0
        ports:
          - "9097:9092"
        env:
          KAFKA_CFG_BROKER_ID: 6
          KAFKA_CFG_BROKER_RACK: zone3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka6
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

  test360:
    runs-on: ubuntu-latest
    container:
      image: cimg/go:1.22
      env:
        GO111MODULE: "on"
        KAFKA_TOPICS_TEST_ZK_ADDR: zookeeper:2181
        KAFKA_TOPICS_TEST_KAFKA_ADDR: kafka1:9092
    steps:
    - name: Check out repository code 
      uses: actions/checkout@v3
    - name: Go setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
    - name: Display Go version
      run: go version
    - name: Run tests
      run: make test-v2
      env:
        KAFKA_TOPICS_TEST_ZK_ADDR: zookeeper:2181
        KAFKA_TOPICS_TEST_KAFKA_ADDR: kafka1:9092
        KAFKA_TOPICS_TEST_BROKER_ADMIN_SECURITY: 1

    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - "2181:2181"
        env:
          ALLOW_ANONYMOUS_LOGIN: yes

      kafka1:
        image: bitnami/kafka:3.6.0
        ports:
          - "9092:9092"
        env:
          KAFKA_CFG_BROKER_ID: 1
          KAFKA_CFG_BROKER_RACK: zone1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka1
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka2:
        image: bitnami/kafka:3.6.0
        ports:
          - "9093:9092"
        env:
          KAFKA_CFG_BROKER_ID: 2
          KAFKA_CFG_BROKER_RACK: zone1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka2
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka3:
        image: bitnami/kafka:3.6.0
        ports:
          - "9094:9092"
        env:
          KAFKA_CFG_BROKER_ID: 3
          KAFKA_CFG_BROKER_RACK: zone2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka3
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka4:
        image: bitnami/kafka:3.6.0
        ports:
          - "9095:9092"
        env:
          KAFKA_CFG_BROKER_ID: 4
          KAFKA_CFG_BROKER_RACK: zone2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka4
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka5:
        image: bitnami/kafka:3.6.0
        ports:
          - "9096:9092"
        env:
          KAFKA_CFG_BROKER_ID: 5
          KAFKA_CFG_BROKER_RACK: zone3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka5
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

      kafka6:
        image: bitnami/kafka:3.6.0
        ports:
          - "9097:9092"
        env:
          KAFKA_CFG_BROKER_ID: 6
          KAFKA_CFG_BROKER_RACK: zone3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_ADVERTISED_HOST_NAME: kafka6
          KAFKA_CFG_ADVERTISED_PORT: 9092
          KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
          KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
